<?xml version="1.0" encoding="utf-8"?>

<!--
Title: Sports.xml
Author: Colby Robins
Student Number: c3430421
Date: 11/08/2023 (DD/MM/YY)

This is the sports category of games, it includes information for the following games:
Face Punch!
Handball
Ultimate Frisbee
-->

<!DOCTYPE gameList [
<!ELEMENT gameList (game+)>
<!ELEMENT game (name, description)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (date, author+, playerLimit*, subject, gradeLvl, searchTag*, cost?, equipment+, review*, picture+, url)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT author ((creator | brand)+)> 
<!ELEMENT creator (#PCDATA)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT playerLimit (#PCDATA)>
<!ELEMENT subject (#PCDATA)>
<!ELEMENT gradeLvl (#PCDATA)>
<!ELEMENT searchTag (#PCDATA)>
<!ELEMENT cost (#PCDATA)>
<!ELEMENT equipment (equipmentName, addCost)>
<!ELEMENT equipmentName (#PCDATA)>
<!ELEMENT addCost (#PCDATA)>
<!ELEMENT review (reviewDescription, reviewScore)>
<!ELEMENT reviewDescription (#PCDATA)>
<!ELEMENT reviewScore (#PCDATA)>
<!ELEMENT picture (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ENTITY Star "â˜…">
<!ENTITY Year "Yr">
<!ENTITY Kieran "God Web Developer Himself">
]>

<gameList>
    <game>
        <name>Face Punch!</name>
        <description>
            <date>19/8/1995</date>
            <author>
                <creator>Mike Tyson</creator>
            </author>
            <playerLimit>2</playerLimit>
            <subject>PE</subject>
            <gradeLvl>Pre-school</gradeLvl>
            <searchTag>Punch</searchTag>
            <cost>Possible teeth</cost>
            <equipment>
                <equipmentName>Boxing gloves</equipmentName>
                <addCost>$35</addCost>
            </equipment>
            <review>
                <reviewDescription>Super fun game! Helped me relieve a lot of stress when I played with my friend Billy - Fred</reviewDescription>
                <reviewScore>4.5 Star</reviewScore>
            </review>
            <review>
                <reviewDescription>Somebody please take me to the hospital - Billy</reviewDescription>
                <reviewScore>1 Star</reviewScore>
            </review>
            <picture>FacePunch.jpg</picture>
            <url></url>
        </description>
    </game>

    <game>
        <name>Handball</name>
        <description>
            <date>1/1/1</date>
            <author>
                <creator>Unknown</creator>
            </author>
            <playerLimit>2 Minimum</playerLimit>
            <subject>Recess</subject>
            <gradeLvl>Year 5</gradeLvl>
            <searchTag>Handball</searchTag>
            <cost>Free</cost>
            <equipment>
                <equipmentName>Ball</equipmentName>
                <addCost>$3</addCost>
            </equipment>
            <review>
                <reviewDescription>Mate, this is the greatest game on God's green earth - Tommy, Year 5 student</reviewDescription>
                <reviewScore>5 Star</reviewScore>
            </review>
            <picture>Handball.jpg</picture>
            <url>https://en.wikipedia.org/wiki/Handball_(schoolyard_game)</url>
        </description>
    </game>

    <game>
        <name>Ultimate Frisbee</name>
        <description>
            <date>1968</date>
            <author>
                <creator>Joel Silver</creator>
            </author>
            <playerLimit>5-7</playerLimit>
            <subject>PE</subject>
            <gradeLvl>Year 2</gradeLvl>
            <searchTag>Ultimate</searchTag>
            <cost>$60</cost>
            <equipment>
                <equipmentName>Net</equipmentName>
                <addCost>$40</addCost>
            </equipment>
            <equipment>
                <equipmentName>Frisbee</equipmentName>
                <addCost>$20</addCost>
            </equipment>
            <review>
                <reviewDescription>This game is rubbish for real - George</reviewDescription>
                <reviewScore>2.5 Star</reviewScore>
            </review>
            <picture>UltimateFrisbee.jpg</picture>
            <url>https://en.wikipedia.org/wiki/Ultimate_(sport)</url>
        </description>
    </game>
</gameList>